### ISSUE TITLE
[DISCOVERY] Implement automated work-around for missing line number from PHP-CPG / Joern 

### ISSUE THREAD

**Issue by compaluca** [testable-eu/sast-tp-framework#42]
Related to https://github.com/testable-eu/sast-testability-patterns/issues/9#issuecomment-1424162773

When PHP discovery rule ends with `.size`, then replace with 
```
.repeat(_.astParent)(_.until(_.filter(x => x.lineNumber.getOrElse(-1) != -1))).location.toJson
```

@mal-tee : do you confirm this is the work-around?

**Comment by mal-tee** [comment]
Yes! I used the same string as in the linked comment.

**Comment by compaluca** [comment]
@mal-tee can you help on the comment from @felix-20 ?

**Comment by mal-tee** [comment]
Yes, sounds good! I only had Location.toJson in mind while designing the hotfix, so it totally makes sense to only apply it then.
