### ISSUE TITLE
Docker Build CodeQL : install script mission +x 

### ISSUE THREAD

**Issue by julien-ft-64** [testable-eu/sast-tp-framework#78]
When trying to docker-compose build under linux:

`=> ERROR [12/12] RUN /SAST/sast/codeql/codeql-install.sh /SAST/sast/code  0.3s
------                                                                          
 > [12/12] RUN /SAST/sast/codeql/codeql-install.sh /SAST/sast/codeql/codeql-versions-list.yaml:
0.267 /bin/sh: 1: /SAST/sast/codeql/codeql-install.sh: Permission denied
------
Dockerfile:27
--------------------
  25 |     
  26 |     # codeql installation
  27 | >>> RUN ${CODEQL_INTERFACE_DIR}/codeql-install.sh ${CODEQL_INTERFACE_DIR}/codeql-versions-list.yaml
`

codeql-install.sh is missing Executable bit so won't be run
running `chmod +x SAST/sast/codeql/codeql-install.sh` before fixes the issues, file should be comitted with the exec bit

keep on the good work!

**Comment by compaluca** [comment]
Thanks for raising the issue. The problem should be solved. 

We really need to put in place a pipeline to automatically test that the docker-compose builds properly to avoid this mistakes, issue #79 added.
